# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  triggerWorlflow:
    name: Trigger another action worflow
    runs-on: macos-latest
    env:
      ACCESS_TOKEN: ${{ secrets.REPO_WORKFLOW_ACCESS_TOKEN }}
    steps:
      - name: create repository dispatch event and run
        if: env.REPOSITORY_DESPATCH == 'true'
        shell: pwsh
        run: |
          $token = $env:ACCESS_TOKEN
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \-H "Authorization: token $token"
          https://api.github.com/repos/urjhams/json-upload/dispatches \
          -d '{"event_type":"upload-the-json"}'
          
