# This is a basic workflow to help you get started with Actions

name: Test workflow
# test comment 2
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  addFile:
    name: add file
    runs-on: macos-latest
    steps:
      # check out the repository
      - name: check out
        uses: actions/checkout@v2
        
      # filter to detect different in files
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            targetFolder:
              - '.github/workflows/**'
      
      - name: update file and push to remote
        if: steps.filter.outputs.targetFolder == 'true'
        run: |
          mkdir -p ./TestFolder
          mv ./Test3.txt ./TestFolder
          
          git add -A
          git commit -m "moving test.txt"
          git push
#   triggerWorlflow:
#     name: Trigger another action worflow
#     runs-on: macos-latest
#     env:
#       ACCESS_TOKEN: ${{ secrets.REPO_WORKFLOW_ACCESS_TOKEN }}
#     steps:
#       - name: create repository dispatch event and run
#         run: |
#           curl \
#           -X POST \
#           -H "Accept: application/vnd.github.v3+json" \
#           -H "Authorization: token $ACCESS_TOKEN" \
#           https://api.github.com/repos/urjhams/json-upload/dispatches \
#           -d '{"event_type":"upload-the-json", "client_payload": { "value":"tested" }}'
          
