name: Test Workflow

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bumpTag:
    name: Generate and bump tag number
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      # Fetches all tags for the repo
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
        
      # Check if the app version has a git tag
      # If there is a git tag for the version set the variable 'tagged' to 0
      # if there is NOT a git tag for the version set the variable 'tagged' to 1
      - name: 'Check: package version has corrosponding git tag'
        if: ${{ always() }} # force run even if there is no tag (which mean the previous step failed)
        id: tagged
        shell: bash
        run: |
          git show-ref --tags --verify --quiet -- \
          "refs/tags/v${{ steps.package.outputs.version }}" && \
          echo "::set-output name=hasTag::0" || \
          echo "::set-output name=hasTag::1"
        
      - name: has tag case
        if: steps.tagged.ouput.hasTag != 1
        run: echo "has tag"
        
      - name: has no tag case
        if: steps.tagged.output.hasTag == 1
        run: echo "has no tags"
